### ISSUE TITLE
Optodes positions

### ISSUE THREAD

**Issue by Edouard2laire** [rob-luke/BIDS-NIRS-Tapping#3]
Hello, 

I am not sure if I should ask the question here, or in a BIDS discussion group but when importing this dataset, should we import the optodes coordinate written in the .snirf file or from the optodes.tsv file? 

I also noticed that the event are both in the .snirf and events.tsv. 

Edouard

**Comment by rob-luke** [comment]
Hi @Edouard2laire 

Good question. There are many fields duplicated between the underlying data file format (here snirf) and the bids files. For example sampling rate, number of channels, etc. The information should be the same in both the data and bids files. Ideally in the future the bids validator will actually check the data is matching. 

However, the optodes positions are a special case. Because the SNIRF format does not specify the optode coordinate frame it can be ambiguous as to how to interpret the snirf location data. So I recommend using the bids data in this case. 

See https://github.com/fNIRS/snirf/pull/94 to follow for reference info.
